version: "3"
services:
  ventoy: 
    image: thedrobe/iventoy-docker
    network_mode: "host"
    restart: unless-stopped
    privileged: true
    stop_signal: SIGINT
    volumes:
     - ./iso:/app/iso
